#!/bin/bash
echo -e "-------------------------------------------------------\n"
echo    "--------Iniciando constulta entrada DNS------------------"
echo""

for url in $(echo 'A,ANY,MX,NS,SOA,HINFO,AXFR,TXT' | awk -F , '{print$1"\n"$2"\n"$3"\n"$4"\n"$5"\n"$6"\n"$7"\n"$8}');
do
        echo -e "-------------------------\n Entrada tipo: $url \n\n" $(host -t $url $1)
done

echo -e "-------------------------------------------------------\n"
echo -e "DNS Reverso\n" 

ipm=`host -t a $1 | awk '{print$4}' | sed '2d'`
host $ipm

echo -e "-------------------------------------------------------\n"
echo    "--------Consulta de entradas DNS finalizadas"------------
